// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: owned_Items_pb.proto

package com.ch8n.thatsmine;

/**
 * Protobuf type {@code ProtoOwnedItem}
 */
public  final class ProtoOwnedItem extends
    com.google.protobuf.GeneratedMessageLite<
        ProtoOwnedItem, ProtoOwnedItem.Builder> implements
    // @@protoc_insertion_point(message_implements:ProtoOwnedItem)
    ProtoOwnedItemOrBuilder {
  private ProtoOwnedItem() {
    itemId_ = "";
    itemName_ = "";
    itemDescription_ = "";
    imageUrl_ = "";
    originName_ = "";
  }
  /**
   * Protobuf enum {@code ProtoOwnedItem.Origin}
   */
  public enum Origin
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>Unknown = 0;</code>
     */
    Unknown(0),
    /**
     * <code>Gifted = 1;</code>
     */
    Gifted(1),
    /**
     * <code>Purchased = 2;</code>
     */
    Purchased(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Unknown = 0;</code>
     */
    public static final int Unknown_VALUE = 0;
    /**
     * <code>Gifted = 1;</code>
     */
    public static final int Gifted_VALUE = 1;
    /**
     * <code>Purchased = 2;</code>
     */
    public static final int Purchased_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Origin valueOf(int value) {
      return forNumber(value);
    }

    public static Origin forNumber(int value) {
      switch (value) {
        case 0: return Unknown;
        case 1: return Gifted;
        case 2: return Purchased;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Origin>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Origin> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Origin>() {
            public Origin findValueByNumber(int number) {
              return Origin.forNumber(number);
            }
          };

    private final int value;

    private Origin(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ProtoOwnedItem.Origin)
  }

  public static final int ITEMID_FIELD_NUMBER = 1;
  private java.lang.String itemId_;
  /**
   * <code>optional string itemId = 1;</code>
   */
  public java.lang.String getItemId() {
    return itemId_;
  }
  /**
   * <code>optional string itemId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getItemIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(itemId_);
  }
  /**
   * <code>optional string itemId = 1;</code>
   */
  private void setItemId(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    itemId_ = value;
  }
  /**
   * <code>optional string itemId = 1;</code>
   */
  private void clearItemId() {
    
    itemId_ = getDefaultInstance().getItemId();
  }
  /**
   * <code>optional string itemId = 1;</code>
   */
  private void setItemIdBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    itemId_ = value.toStringUtf8();
  }

  public static final int ITEMNAME_FIELD_NUMBER = 2;
  private java.lang.String itemName_;
  /**
   * <code>optional string itemName = 2;</code>
   */
  public java.lang.String getItemName() {
    return itemName_;
  }
  /**
   * <code>optional string itemName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getItemNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(itemName_);
  }
  /**
   * <code>optional string itemName = 2;</code>
   */
  private void setItemName(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    itemName_ = value;
  }
  /**
   * <code>optional string itemName = 2;</code>
   */
  private void clearItemName() {
    
    itemName_ = getDefaultInstance().getItemName();
  }
  /**
   * <code>optional string itemName = 2;</code>
   */
  private void setItemNameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    itemName_ = value.toStringUtf8();
  }

  public static final int ITEMDESCRIPTION_FIELD_NUMBER = 3;
  private java.lang.String itemDescription_;
  /**
   * <code>optional string itemDescription = 3;</code>
   */
  public java.lang.String getItemDescription() {
    return itemDescription_;
  }
  /**
   * <code>optional string itemDescription = 3;</code>
   */
  public com.google.protobuf.ByteString
      getItemDescriptionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(itemDescription_);
  }
  /**
   * <code>optional string itemDescription = 3;</code>
   */
  private void setItemDescription(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    itemDescription_ = value;
  }
  /**
   * <code>optional string itemDescription = 3;</code>
   */
  private void clearItemDescription() {
    
    itemDescription_ = getDefaultInstance().getItemDescription();
  }
  /**
   * <code>optional string itemDescription = 3;</code>
   */
  private void setItemDescriptionBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    itemDescription_ = value.toStringUtf8();
  }

  public static final int OWNEDAT_FIELD_NUMBER = 4;
  private long ownedAt_;
  /**
   * <pre>
   * long
   * </pre>
   *
   * <code>optional int64 ownedAt = 4;</code>
   */
  public long getOwnedAt() {
    return ownedAt_;
  }
  /**
   * <pre>
   * long
   * </pre>
   *
   * <code>optional int64 ownedAt = 4;</code>
   */
  private void setOwnedAt(long value) {
    
    ownedAt_ = value;
  }
  /**
   * <pre>
   * long
   * </pre>
   *
   * <code>optional int64 ownedAt = 4;</code>
   */
  private void clearOwnedAt() {
    
    ownedAt_ = 0L;
  }

  public static final int INVENTORY_FIELD_NUMBER = 5;
  private int inventory_;
  /**
   * <pre>
   * Int
   * </pre>
   *
   * <code>optional int32 inventory = 5;</code>
   */
  public int getInventory() {
    return inventory_;
  }
  /**
   * <pre>
   * Int
   * </pre>
   *
   * <code>optional int32 inventory = 5;</code>
   */
  private void setInventory(int value) {
    
    inventory_ = value;
  }
  /**
   * <pre>
   * Int
   * </pre>
   *
   * <code>optional int32 inventory = 5;</code>
   */
  private void clearInventory() {
    
    inventory_ = 0;
  }

  public static final int EXPIRESIN_FIELD_NUMBER = 6;
  private long expiresIn_;
  /**
   * <pre>
   * long
   * </pre>
   *
   * <code>optional int64 expiresIn = 6;</code>
   */
  public long getExpiresIn() {
    return expiresIn_;
  }
  /**
   * <pre>
   * long
   * </pre>
   *
   * <code>optional int64 expiresIn = 6;</code>
   */
  private void setExpiresIn(long value) {
    
    expiresIn_ = value;
  }
  /**
   * <pre>
   * long
   * </pre>
   *
   * <code>optional int64 expiresIn = 6;</code>
   */
  private void clearExpiresIn() {
    
    expiresIn_ = 0L;
  }

  public static final int IMAGEURL_FIELD_NUMBER = 7;
  private java.lang.String imageUrl_;
  /**
   * <code>optional string imageUrl = 7;</code>
   */
  public java.lang.String getImageUrl() {
    return imageUrl_;
  }
  /**
   * <code>optional string imageUrl = 7;</code>
   */
  public com.google.protobuf.ByteString
      getImageUrlBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(imageUrl_);
  }
  /**
   * <code>optional string imageUrl = 7;</code>
   */
  private void setImageUrl(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    imageUrl_ = value;
  }
  /**
   * <code>optional string imageUrl = 7;</code>
   */
  private void clearImageUrl() {
    
    imageUrl_ = getDefaultInstance().getImageUrl();
  }
  /**
   * <code>optional string imageUrl = 7;</code>
   */
  private void setImageUrlBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    imageUrl_ = value.toStringUtf8();
  }

  public static final int ORIGINNAME_FIELD_NUMBER = 8;
  private java.lang.String originName_;
  /**
   * <code>optional string originName = 8;</code>
   */
  public java.lang.String getOriginName() {
    return originName_;
  }
  /**
   * <code>optional string originName = 8;</code>
   */
  public com.google.protobuf.ByteString
      getOriginNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(originName_);
  }
  /**
   * <code>optional string originName = 8;</code>
   */
  private void setOriginName(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    originName_ = value;
  }
  /**
   * <code>optional string originName = 8;</code>
   */
  private void clearOriginName() {
    
    originName_ = getDefaultInstance().getOriginName();
  }
  /**
   * <code>optional string originName = 8;</code>
   */
  private void setOriginNameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    originName_ = value.toStringUtf8();
  }

  public static final int ORIGIN_FIELD_NUMBER = 9;
  private int origin_;
  /**
   * <code>optional .ProtoOwnedItem.Origin origin = 9;</code>
   */
  public int getOriginValue() {
    return origin_;
  }
  /**
   * <code>optional .ProtoOwnedItem.Origin origin = 9;</code>
   */
  public com.ch8n.thatsmine.ProtoOwnedItem.Origin getOrigin() {
    com.ch8n.thatsmine.ProtoOwnedItem.Origin result = com.ch8n.thatsmine.ProtoOwnedItem.Origin.forNumber(origin_);
    return result == null ? com.ch8n.thatsmine.ProtoOwnedItem.Origin.UNRECOGNIZED : result;
  }
  /**
   * <code>optional .ProtoOwnedItem.Origin origin = 9;</code>
   */
  private void setOriginValue(int value) {
      origin_ = value;
  }
  /**
   * <code>optional .ProtoOwnedItem.Origin origin = 9;</code>
   */
  private void setOrigin(com.ch8n.thatsmine.ProtoOwnedItem.Origin value) {
    if (value == null) {
      throw new NullPointerException();
    }
    
    origin_ = value.getNumber();
  }
  /**
   * <code>optional .ProtoOwnedItem.Origin origin = 9;</code>
   */
  private void clearOrigin() {
    
    origin_ = 0;
  }

  public static final int ISFAVOURITE_FIELD_NUMBER = 10;
  private boolean isFavourite_;
  /**
   * <code>optional bool isFavourite = 10;</code>
   */
  public boolean getIsFavourite() {
    return isFavourite_;
  }
  /**
   * <code>optional bool isFavourite = 10;</code>
   */
  private void setIsFavourite(boolean value) {
    
    isFavourite_ = value;
  }
  /**
   * <code>optional bool isFavourite = 10;</code>
   */
  private void clearIsFavourite() {
    
    isFavourite_ = false;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!itemId_.isEmpty()) {
      output.writeString(1, getItemId());
    }
    if (!itemName_.isEmpty()) {
      output.writeString(2, getItemName());
    }
    if (!itemDescription_.isEmpty()) {
      output.writeString(3, getItemDescription());
    }
    if (ownedAt_ != 0L) {
      output.writeInt64(4, ownedAt_);
    }
    if (inventory_ != 0) {
      output.writeInt32(5, inventory_);
    }
    if (expiresIn_ != 0L) {
      output.writeInt64(6, expiresIn_);
    }
    if (!imageUrl_.isEmpty()) {
      output.writeString(7, getImageUrl());
    }
    if (!originName_.isEmpty()) {
      output.writeString(8, getOriginName());
    }
    if (origin_ != com.ch8n.thatsmine.ProtoOwnedItem.Origin.Unknown.getNumber()) {
      output.writeEnum(9, origin_);
    }
    if (isFavourite_ != false) {
      output.writeBool(10, isFavourite_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!itemId_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getItemId());
    }
    if (!itemName_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(2, getItemName());
    }
    if (!itemDescription_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(3, getItemDescription());
    }
    if (ownedAt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, ownedAt_);
    }
    if (inventory_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, inventory_);
    }
    if (expiresIn_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, expiresIn_);
    }
    if (!imageUrl_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(7, getImageUrl());
    }
    if (!originName_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(8, getOriginName());
    }
    if (origin_ != com.ch8n.thatsmine.ProtoOwnedItem.Origin.Unknown.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(9, origin_);
    }
    if (isFavourite_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, isFavourite_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static com.ch8n.thatsmine.ProtoOwnedItem parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ch8n.thatsmine.ProtoOwnedItem parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ch8n.thatsmine.ProtoOwnedItem parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ch8n.thatsmine.ProtoOwnedItem parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ch8n.thatsmine.ProtoOwnedItem parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.ch8n.thatsmine.ProtoOwnedItem parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.ch8n.thatsmine.ProtoOwnedItem parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.ch8n.thatsmine.ProtoOwnedItem parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.ch8n.thatsmine.ProtoOwnedItem parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.ch8n.thatsmine.ProtoOwnedItem parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ch8n.thatsmine.ProtoOwnedItem prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code ProtoOwnedItem}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.ch8n.thatsmine.ProtoOwnedItem, Builder> implements
      // @@protoc_insertion_point(builder_implements:ProtoOwnedItem)
      com.ch8n.thatsmine.ProtoOwnedItemOrBuilder {
    // Construct using com.ch8n.thatsmine.ProtoOwnedItem.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional string itemId = 1;</code>
     */
    public java.lang.String getItemId() {
      return instance.getItemId();
    }
    /**
     * <code>optional string itemId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getItemIdBytes() {
      return instance.getItemIdBytes();
    }
    /**
     * <code>optional string itemId = 1;</code>
     */
    public Builder setItemId(
        java.lang.String value) {
      copyOnWrite();
      instance.setItemId(value);
      return this;
    }
    /**
     * <code>optional string itemId = 1;</code>
     */
    public Builder clearItemId() {
      copyOnWrite();
      instance.clearItemId();
      return this;
    }
    /**
     * <code>optional string itemId = 1;</code>
     */
    public Builder setItemIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setItemIdBytes(value);
      return this;
    }

    /**
     * <code>optional string itemName = 2;</code>
     */
    public java.lang.String getItemName() {
      return instance.getItemName();
    }
    /**
     * <code>optional string itemName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getItemNameBytes() {
      return instance.getItemNameBytes();
    }
    /**
     * <code>optional string itemName = 2;</code>
     */
    public Builder setItemName(
        java.lang.String value) {
      copyOnWrite();
      instance.setItemName(value);
      return this;
    }
    /**
     * <code>optional string itemName = 2;</code>
     */
    public Builder clearItemName() {
      copyOnWrite();
      instance.clearItemName();
      return this;
    }
    /**
     * <code>optional string itemName = 2;</code>
     */
    public Builder setItemNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setItemNameBytes(value);
      return this;
    }

    /**
     * <code>optional string itemDescription = 3;</code>
     */
    public java.lang.String getItemDescription() {
      return instance.getItemDescription();
    }
    /**
     * <code>optional string itemDescription = 3;</code>
     */
    public com.google.protobuf.ByteString
        getItemDescriptionBytes() {
      return instance.getItemDescriptionBytes();
    }
    /**
     * <code>optional string itemDescription = 3;</code>
     */
    public Builder setItemDescription(
        java.lang.String value) {
      copyOnWrite();
      instance.setItemDescription(value);
      return this;
    }
    /**
     * <code>optional string itemDescription = 3;</code>
     */
    public Builder clearItemDescription() {
      copyOnWrite();
      instance.clearItemDescription();
      return this;
    }
    /**
     * <code>optional string itemDescription = 3;</code>
     */
    public Builder setItemDescriptionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setItemDescriptionBytes(value);
      return this;
    }

    /**
     * <pre>
     * long
     * </pre>
     *
     * <code>optional int64 ownedAt = 4;</code>
     */
    public long getOwnedAt() {
      return instance.getOwnedAt();
    }
    /**
     * <pre>
     * long
     * </pre>
     *
     * <code>optional int64 ownedAt = 4;</code>
     */
    public Builder setOwnedAt(long value) {
      copyOnWrite();
      instance.setOwnedAt(value);
      return this;
    }
    /**
     * <pre>
     * long
     * </pre>
     *
     * <code>optional int64 ownedAt = 4;</code>
     */
    public Builder clearOwnedAt() {
      copyOnWrite();
      instance.clearOwnedAt();
      return this;
    }

    /**
     * <pre>
     * Int
     * </pre>
     *
     * <code>optional int32 inventory = 5;</code>
     */
    public int getInventory() {
      return instance.getInventory();
    }
    /**
     * <pre>
     * Int
     * </pre>
     *
     * <code>optional int32 inventory = 5;</code>
     */
    public Builder setInventory(int value) {
      copyOnWrite();
      instance.setInventory(value);
      return this;
    }
    /**
     * <pre>
     * Int
     * </pre>
     *
     * <code>optional int32 inventory = 5;</code>
     */
    public Builder clearInventory() {
      copyOnWrite();
      instance.clearInventory();
      return this;
    }

    /**
     * <pre>
     * long
     * </pre>
     *
     * <code>optional int64 expiresIn = 6;</code>
     */
    public long getExpiresIn() {
      return instance.getExpiresIn();
    }
    /**
     * <pre>
     * long
     * </pre>
     *
     * <code>optional int64 expiresIn = 6;</code>
     */
    public Builder setExpiresIn(long value) {
      copyOnWrite();
      instance.setExpiresIn(value);
      return this;
    }
    /**
     * <pre>
     * long
     * </pre>
     *
     * <code>optional int64 expiresIn = 6;</code>
     */
    public Builder clearExpiresIn() {
      copyOnWrite();
      instance.clearExpiresIn();
      return this;
    }

    /**
     * <code>optional string imageUrl = 7;</code>
     */
    public java.lang.String getImageUrl() {
      return instance.getImageUrl();
    }
    /**
     * <code>optional string imageUrl = 7;</code>
     */
    public com.google.protobuf.ByteString
        getImageUrlBytes() {
      return instance.getImageUrlBytes();
    }
    /**
     * <code>optional string imageUrl = 7;</code>
     */
    public Builder setImageUrl(
        java.lang.String value) {
      copyOnWrite();
      instance.setImageUrl(value);
      return this;
    }
    /**
     * <code>optional string imageUrl = 7;</code>
     */
    public Builder clearImageUrl() {
      copyOnWrite();
      instance.clearImageUrl();
      return this;
    }
    /**
     * <code>optional string imageUrl = 7;</code>
     */
    public Builder setImageUrlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setImageUrlBytes(value);
      return this;
    }

    /**
     * <code>optional string originName = 8;</code>
     */
    public java.lang.String getOriginName() {
      return instance.getOriginName();
    }
    /**
     * <code>optional string originName = 8;</code>
     */
    public com.google.protobuf.ByteString
        getOriginNameBytes() {
      return instance.getOriginNameBytes();
    }
    /**
     * <code>optional string originName = 8;</code>
     */
    public Builder setOriginName(
        java.lang.String value) {
      copyOnWrite();
      instance.setOriginName(value);
      return this;
    }
    /**
     * <code>optional string originName = 8;</code>
     */
    public Builder clearOriginName() {
      copyOnWrite();
      instance.clearOriginName();
      return this;
    }
    /**
     * <code>optional string originName = 8;</code>
     */
    public Builder setOriginNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setOriginNameBytes(value);
      return this;
    }

    /**
     * <code>optional .ProtoOwnedItem.Origin origin = 9;</code>
     */
    public int getOriginValue() {
      return instance.getOriginValue();
    }
    /**
     * <code>optional .ProtoOwnedItem.Origin origin = 9;</code>
     */
    public Builder setOriginValue(int value) {
      copyOnWrite();
      instance.setOriginValue(value);
      return this;
    }
    /**
     * <code>optional .ProtoOwnedItem.Origin origin = 9;</code>
     */
    public com.ch8n.thatsmine.ProtoOwnedItem.Origin getOrigin() {
      return instance.getOrigin();
    }
    /**
     * <code>optional .ProtoOwnedItem.Origin origin = 9;</code>
     */
    public Builder setOrigin(com.ch8n.thatsmine.ProtoOwnedItem.Origin value) {
      copyOnWrite();
      instance.setOrigin(value);
      return this;
    }
    /**
     * <code>optional .ProtoOwnedItem.Origin origin = 9;</code>
     */
    public Builder clearOrigin() {
      copyOnWrite();
      instance.clearOrigin();
      return this;
    }

    /**
     * <code>optional bool isFavourite = 10;</code>
     */
    public boolean getIsFavourite() {
      return instance.getIsFavourite();
    }
    /**
     * <code>optional bool isFavourite = 10;</code>
     */
    public Builder setIsFavourite(boolean value) {
      copyOnWrite();
      instance.setIsFavourite(value);
      return this;
    }
    /**
     * <code>optional bool isFavourite = 10;</code>
     */
    public Builder clearIsFavourite() {
      copyOnWrite();
      instance.clearIsFavourite();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ProtoOwnedItem)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.ch8n.thatsmine.ProtoOwnedItem();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.ch8n.thatsmine.ProtoOwnedItem other = (com.ch8n.thatsmine.ProtoOwnedItem) arg1;
        itemId_ = visitor.visitString(!itemId_.isEmpty(), itemId_,
            !other.itemId_.isEmpty(), other.itemId_);
        itemName_ = visitor.visitString(!itemName_.isEmpty(), itemName_,
            !other.itemName_.isEmpty(), other.itemName_);
        itemDescription_ = visitor.visitString(!itemDescription_.isEmpty(), itemDescription_,
            !other.itemDescription_.isEmpty(), other.itemDescription_);
        ownedAt_ = visitor.visitLong(ownedAt_ != 0L, ownedAt_,
            other.ownedAt_ != 0L, other.ownedAt_);
        inventory_ = visitor.visitInt(inventory_ != 0, inventory_,
            other.inventory_ != 0, other.inventory_);
        expiresIn_ = visitor.visitLong(expiresIn_ != 0L, expiresIn_,
            other.expiresIn_ != 0L, other.expiresIn_);
        imageUrl_ = visitor.visitString(!imageUrl_.isEmpty(), imageUrl_,
            !other.imageUrl_.isEmpty(), other.imageUrl_);
        originName_ = visitor.visitString(!originName_.isEmpty(), originName_,
            !other.originName_.isEmpty(), other.originName_);
        origin_ = visitor.visitInt(origin_ != 0, origin_,    other.origin_ != 0, other.origin_);
        isFavourite_ = visitor.visitBoolean(isFavourite_ != false, isFavourite_,
            other.isFavourite_ != false, other.isFavourite_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                itemId_ = s;
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();

                itemName_ = s;
                break;
              }
              case 26: {
                String s = input.readStringRequireUtf8();

                itemDescription_ = s;
                break;
              }
              case 32: {

                ownedAt_ = input.readInt64();
                break;
              }
              case 40: {

                inventory_ = input.readInt32();
                break;
              }
              case 48: {

                expiresIn_ = input.readInt64();
                break;
              }
              case 58: {
                String s = input.readStringRequireUtf8();

                imageUrl_ = s;
                break;
              }
              case 66: {
                String s = input.readStringRequireUtf8();

                originName_ = s;
                break;
              }
              case 72: {
                int rawValue = input.readEnum();

                origin_ = rawValue;
                break;
              }
              case 80: {

                isFavourite_ = input.readBool();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.ch8n.thatsmine.ProtoOwnedItem.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:ProtoOwnedItem)
  private static final com.ch8n.thatsmine.ProtoOwnedItem DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ProtoOwnedItem();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.ch8n.thatsmine.ProtoOwnedItem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ProtoOwnedItem> PARSER;

  public static com.google.protobuf.Parser<ProtoOwnedItem> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

