// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: owned_Items_pb.proto

package com.ch8n.thatsmine;

public interface ProtoOwnedItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProtoOwnedItem)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string itemId = 1;</code>
   */
  java.lang.String getItemId();
  /**
   * <code>optional string itemId = 1;</code>
   */
  com.google.protobuf.ByteString
      getItemIdBytes();

  /**
   * <code>optional string itemName = 2;</code>
   */
  java.lang.String getItemName();
  /**
   * <code>optional string itemName = 2;</code>
   */
  com.google.protobuf.ByteString
      getItemNameBytes();

  /**
   * <code>optional string itemDescription = 3;</code>
   */
  java.lang.String getItemDescription();
  /**
   * <code>optional string itemDescription = 3;</code>
   */
  com.google.protobuf.ByteString
      getItemDescriptionBytes();

  /**
   * <pre>
   * long
   * </pre>
   *
   * <code>optional int64 ownedAt = 4;</code>
   */
  long getOwnedAt();

  /**
   * <pre>
   * Int
   * </pre>
   *
   * <code>optional int32 inventory = 5;</code>
   */
  int getInventory();

  /**
   * <pre>
   * long
   * </pre>
   *
   * <code>optional int64 expiresIn = 6;</code>
   */
  long getExpiresIn();

  /**
   * <code>optional string imageUrl = 7;</code>
   */
  java.lang.String getImageUrl();
  /**
   * <code>optional string imageUrl = 7;</code>
   */
  com.google.protobuf.ByteString
      getImageUrlBytes();

  /**
   * <code>optional string originName = 8;</code>
   */
  java.lang.String getOriginName();
  /**
   * <code>optional string originName = 8;</code>
   */
  com.google.protobuf.ByteString
      getOriginNameBytes();

  /**
   * <code>optional .ProtoOwnedItem.Origin origin = 9;</code>
   */
  int getOriginValue();
  /**
   * <code>optional .ProtoOwnedItem.Origin origin = 9;</code>
   */
  com.ch8n.thatsmine.ProtoOwnedItem.Origin getOrigin();

  /**
   * <code>optional bool isFavourite = 10;</code>
   */
  boolean getIsFavourite();
}
