// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: owned_Items_pb.proto

package com.ch8n.thatsmine;

public final class OwnedItemsPb {
  private OwnedItemsPb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
