// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: owned_Items_pb.proto

package com.ch8n.thatsmine;

public interface ProtoOwnedItemsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProtoOwnedItems)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .ProtoOwnedItem lastViewItem = 1;</code>
   */
  boolean hasLastViewItem();
  /**
   * <code>optional .ProtoOwnedItem lastViewItem = 1;</code>
   */
  com.ch8n.thatsmine.ProtoOwnedItem getLastViewItem();

  /**
   * <pre>
   * repeated =&gt; list
   * </pre>
   *
   * <code>repeated .ProtoOwnedItem offlineBufferItem = 2;</code>
   */
  java.util.List<com.ch8n.thatsmine.ProtoOwnedItem> 
      getOfflineBufferItemList();
  /**
   * <pre>
   * repeated =&gt; list
   * </pre>
   *
   * <code>repeated .ProtoOwnedItem offlineBufferItem = 2;</code>
   */
  com.ch8n.thatsmine.ProtoOwnedItem getOfflineBufferItem(int index);
  /**
   * <pre>
   * repeated =&gt; list
   * </pre>
   *
   * <code>repeated .ProtoOwnedItem offlineBufferItem = 2;</code>
   */
  int getOfflineBufferItemCount();
}
