// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: settings_pb.proto

package com.ch8n.thatsmine;

/**
 * Protobuf type {@code ProtoSettings}
 */
public  final class ProtoSettings extends
    com.google.protobuf.GeneratedMessageLite<
        ProtoSettings, ProtoSettings.Builder> implements
    // @@protoc_insertion_point(message_implements:ProtoSettings)
    ProtoSettingsOrBuilder {
  private ProtoSettings() {
  }
  /**
   * Protobuf enum {@code ProtoSettings.Theme}
   */
  public enum Theme
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>Light = 0;</code>
     */
    Light(0),
    /**
     * <code>Dark = 1;</code>
     */
    Dark(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Light = 0;</code>
     */
    public static final int Light_VALUE = 0;
    /**
     * <code>Dark = 1;</code>
     */
    public static final int Dark_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Theme valueOf(int value) {
      return forNumber(value);
    }

    public static Theme forNumber(int value) {
      switch (value) {
        case 0: return Light;
        case 1: return Dark;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Theme>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Theme> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Theme>() {
            public Theme findValueByNumber(int number) {
              return Theme.forNumber(number);
            }
          };

    private final int value;

    private Theme(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ProtoSettings.Theme)
  }

  public interface ActiveUserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtoSettings.ActiveUser)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string userId = 1;</code>
     */
    java.lang.String getUserId();
    /**
     * <code>optional string userId = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>optional string userName = 2;</code>
     */
    java.lang.String getUserName();
    /**
     * <code>optional string userName = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>optional string fullName = 3;</code>
     */
    java.lang.String getFullName();
    /**
     * <code>optional string fullName = 3;</code>
     */
    com.google.protobuf.ByteString
        getFullNameBytes();

    /**
     * <code>optional string email = 4;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>optional string email = 4;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();
  }
  /**
   * Protobuf type {@code ProtoSettings.ActiveUser}
   */
  public  static final class ActiveUser extends
      com.google.protobuf.GeneratedMessageLite<
          ActiveUser, ActiveUser.Builder> implements
      // @@protoc_insertion_point(message_implements:ProtoSettings.ActiveUser)
      ActiveUserOrBuilder {
    private ActiveUser() {
      userId_ = "";
      userName_ = "";
      fullName_ = "";
      email_ = "";
    }
    public static final int USERID_FIELD_NUMBER = 1;
    private java.lang.String userId_;
    /**
     * <code>optional string userId = 1;</code>
     */
    public java.lang.String getUserId() {
      return userId_;
    }
    /**
     * <code>optional string userId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(userId_);
    }
    /**
     * <code>optional string userId = 1;</code>
     */
    private void setUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userId_ = value;
    }
    /**
     * <code>optional string userId = 1;</code>
     */
    private void clearUserId() {
      
      userId_ = getDefaultInstance().getUserId();
    }
    /**
     * <code>optional string userId = 1;</code>
     */
    private void setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userId_ = value.toStringUtf8();
    }

    public static final int USERNAME_FIELD_NUMBER = 2;
    private java.lang.String userName_;
    /**
     * <code>optional string userName = 2;</code>
     */
    public java.lang.String getUserName() {
      return userName_;
    }
    /**
     * <code>optional string userName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(userName_);
    }
    /**
     * <code>optional string userName = 2;</code>
     */
    private void setUserName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userName_ = value;
    }
    /**
     * <code>optional string userName = 2;</code>
     */
    private void clearUserName() {
      
      userName_ = getDefaultInstance().getUserName();
    }
    /**
     * <code>optional string userName = 2;</code>
     */
    private void setUserNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userName_ = value.toStringUtf8();
    }

    public static final int FULLNAME_FIELD_NUMBER = 3;
    private java.lang.String fullName_;
    /**
     * <code>optional string fullName = 3;</code>
     */
    public java.lang.String getFullName() {
      return fullName_;
    }
    /**
     * <code>optional string fullName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFullNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(fullName_);
    }
    /**
     * <code>optional string fullName = 3;</code>
     */
    private void setFullName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fullName_ = value;
    }
    /**
     * <code>optional string fullName = 3;</code>
     */
    private void clearFullName() {
      
      fullName_ = getDefaultInstance().getFullName();
    }
    /**
     * <code>optional string fullName = 3;</code>
     */
    private void setFullNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fullName_ = value.toStringUtf8();
    }

    public static final int EMAIL_FIELD_NUMBER = 4;
    private java.lang.String email_;
    /**
     * <code>optional string email = 4;</code>
     */
    public java.lang.String getEmail() {
      return email_;
    }
    /**
     * <code>optional string email = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(email_);
    }
    /**
     * <code>optional string email = 4;</code>
     */
    private void setEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      email_ = value;
    }
    /**
     * <code>optional string email = 4;</code>
     */
    private void clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
    }
    /**
     * <code>optional string email = 4;</code>
     */
    private void setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      email_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!userId_.isEmpty()) {
        output.writeString(1, getUserId());
      }
      if (!userName_.isEmpty()) {
        output.writeString(2, getUserName());
      }
      if (!fullName_.isEmpty()) {
        output.writeString(3, getFullName());
      }
      if (!email_.isEmpty()) {
        output.writeString(4, getEmail());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!userId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getUserId());
      }
      if (!userName_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getUserName());
      }
      if (!fullName_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getFullName());
      }
      if (!email_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getEmail());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.ch8n.thatsmine.ProtoSettings.ActiveUser parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.ch8n.thatsmine.ProtoSettings.ActiveUser parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.ch8n.thatsmine.ProtoSettings.ActiveUser parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.ch8n.thatsmine.ProtoSettings.ActiveUser parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.ch8n.thatsmine.ProtoSettings.ActiveUser parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.ch8n.thatsmine.ProtoSettings.ActiveUser parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.ch8n.thatsmine.ProtoSettings.ActiveUser parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.ch8n.thatsmine.ProtoSettings.ActiveUser parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.ch8n.thatsmine.ProtoSettings.ActiveUser parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.ch8n.thatsmine.ProtoSettings.ActiveUser parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ch8n.thatsmine.ProtoSettings.ActiveUser prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code ProtoSettings.ActiveUser}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.ch8n.thatsmine.ProtoSettings.ActiveUser, Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtoSettings.ActiveUser)
        com.ch8n.thatsmine.ProtoSettings.ActiveUserOrBuilder {
      // Construct using com.ch8n.thatsmine.ProtoSettings.ActiveUser.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string userId = 1;</code>
       */
      public java.lang.String getUserId() {
        return instance.getUserId();
      }
      /**
       * <code>optional string userId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        return instance.getUserIdBytes();
      }
      /**
       * <code>optional string userId = 1;</code>
       */
      public Builder setUserId(
          java.lang.String value) {
        copyOnWrite();
        instance.setUserId(value);
        return this;
      }
      /**
       * <code>optional string userId = 1;</code>
       */
      public Builder clearUserId() {
        copyOnWrite();
        instance.clearUserId();
        return this;
      }
      /**
       * <code>optional string userId = 1;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUserIdBytes(value);
        return this;
      }

      /**
       * <code>optional string userName = 2;</code>
       */
      public java.lang.String getUserName() {
        return instance.getUserName();
      }
      /**
       * <code>optional string userName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        return instance.getUserNameBytes();
      }
      /**
       * <code>optional string userName = 2;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        copyOnWrite();
        instance.setUserName(value);
        return this;
      }
      /**
       * <code>optional string userName = 2;</code>
       */
      public Builder clearUserName() {
        copyOnWrite();
        instance.clearUserName();
        return this;
      }
      /**
       * <code>optional string userName = 2;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUserNameBytes(value);
        return this;
      }

      /**
       * <code>optional string fullName = 3;</code>
       */
      public java.lang.String getFullName() {
        return instance.getFullName();
      }
      /**
       * <code>optional string fullName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFullNameBytes() {
        return instance.getFullNameBytes();
      }
      /**
       * <code>optional string fullName = 3;</code>
       */
      public Builder setFullName(
          java.lang.String value) {
        copyOnWrite();
        instance.setFullName(value);
        return this;
      }
      /**
       * <code>optional string fullName = 3;</code>
       */
      public Builder clearFullName() {
        copyOnWrite();
        instance.clearFullName();
        return this;
      }
      /**
       * <code>optional string fullName = 3;</code>
       */
      public Builder setFullNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setFullNameBytes(value);
        return this;
      }

      /**
       * <code>optional string email = 4;</code>
       */
      public java.lang.String getEmail() {
        return instance.getEmail();
      }
      /**
       * <code>optional string email = 4;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        return instance.getEmailBytes();
      }
      /**
       * <code>optional string email = 4;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        copyOnWrite();
        instance.setEmail(value);
        return this;
      }
      /**
       * <code>optional string email = 4;</code>
       */
      public Builder clearEmail() {
        copyOnWrite();
        instance.clearEmail();
        return this;
      }
      /**
       * <code>optional string email = 4;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEmailBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProtoSettings.ActiveUser)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.ch8n.thatsmine.ProtoSettings.ActiveUser();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.ch8n.thatsmine.ProtoSettings.ActiveUser other = (com.ch8n.thatsmine.ProtoSettings.ActiveUser) arg1;
          userId_ = visitor.visitString(!userId_.isEmpty(), userId_,
              !other.userId_.isEmpty(), other.userId_);
          userName_ = visitor.visitString(!userName_.isEmpty(), userName_,
              !other.userName_.isEmpty(), other.userName_);
          fullName_ = visitor.visitString(!fullName_.isEmpty(), fullName_,
              !other.fullName_.isEmpty(), other.fullName_);
          email_ = visitor.visitString(!email_.isEmpty(), email_,
              !other.email_.isEmpty(), other.email_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  userId_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  userName_ = s;
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  fullName_ = s;
                  break;
                }
                case 34: {
                  String s = input.readStringRequireUtf8();

                  email_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.ch8n.thatsmine.ProtoSettings.ActiveUser.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:ProtoSettings.ActiveUser)
    private static final com.ch8n.thatsmine.ProtoSettings.ActiveUser DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ActiveUser();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.ch8n.thatsmine.ProtoSettings.ActiveUser getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ActiveUser> PARSER;

    public static com.google.protobuf.Parser<ActiveUser> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public static final int NOTIFICATION_ENABLED_FIELD_NUMBER = 1;
  private boolean notificationEnabled_;
  /**
   * <code>optional bool notification_enabled = 1;</code>
   */
  public boolean getNotificationEnabled() {
    return notificationEnabled_;
  }
  /**
   * <code>optional bool notification_enabled = 1;</code>
   */
  private void setNotificationEnabled(boolean value) {
    
    notificationEnabled_ = value;
  }
  /**
   * <code>optional bool notification_enabled = 1;</code>
   */
  private void clearNotificationEnabled() {
    
    notificationEnabled_ = false;
  }

  public static final int LOGGEDIN_FIELD_NUMBER = 2;
  private boolean loggedIn_;
  /**
   * <code>optional bool loggedIn = 2;</code>
   */
  public boolean getLoggedIn() {
    return loggedIn_;
  }
  /**
   * <code>optional bool loggedIn = 2;</code>
   */
  private void setLoggedIn(boolean value) {
    
    loggedIn_ = value;
  }
  /**
   * <code>optional bool loggedIn = 2;</code>
   */
  private void clearLoggedIn() {
    
    loggedIn_ = false;
  }

  public static final int GUESTMODE_FIELD_NUMBER = 3;
  private boolean guestMode_;
  /**
   * <code>optional bool guestMode = 3;</code>
   */
  public boolean getGuestMode() {
    return guestMode_;
  }
  /**
   * <code>optional bool guestMode = 3;</code>
   */
  private void setGuestMode(boolean value) {
    
    guestMode_ = value;
  }
  /**
   * <code>optional bool guestMode = 3;</code>
   */
  private void clearGuestMode() {
    
    guestMode_ = false;
  }

  public static final int ACTIVEUSER_FIELD_NUMBER = 4;
  private com.ch8n.thatsmine.ProtoSettings.ActiveUser activeUser_;
  /**
   * <code>optional .ProtoSettings.ActiveUser activeUser = 4;</code>
   */
  public boolean hasActiveUser() {
    return activeUser_ != null;
  }
  /**
   * <code>optional .ProtoSettings.ActiveUser activeUser = 4;</code>
   */
  public com.ch8n.thatsmine.ProtoSettings.ActiveUser getActiveUser() {
    return activeUser_ == null ? com.ch8n.thatsmine.ProtoSettings.ActiveUser.getDefaultInstance() : activeUser_;
  }
  /**
   * <code>optional .ProtoSettings.ActiveUser activeUser = 4;</code>
   */
  private void setActiveUser(com.ch8n.thatsmine.ProtoSettings.ActiveUser value) {
    if (value == null) {
      throw new NullPointerException();
    }
    activeUser_ = value;
    
    }
  /**
   * <code>optional .ProtoSettings.ActiveUser activeUser = 4;</code>
   */
  private void setActiveUser(
      com.ch8n.thatsmine.ProtoSettings.ActiveUser.Builder builderForValue) {
    activeUser_ = builderForValue.build();
    
  }
  /**
   * <code>optional .ProtoSettings.ActiveUser activeUser = 4;</code>
   */
  private void mergeActiveUser(com.ch8n.thatsmine.ProtoSettings.ActiveUser value) {
    if (activeUser_ != null &&
        activeUser_ != com.ch8n.thatsmine.ProtoSettings.ActiveUser.getDefaultInstance()) {
      activeUser_ =
        com.ch8n.thatsmine.ProtoSettings.ActiveUser.newBuilder(activeUser_).mergeFrom(value).buildPartial();
    } else {
      activeUser_ = value;
    }
    
  }
  /**
   * <code>optional .ProtoSettings.ActiveUser activeUser = 4;</code>
   */
  private void clearActiveUser() {  activeUser_ = null;
    
  }

  public static final int CURRENTTHEME_FIELD_NUMBER = 5;
  private int currentTheme_;
  /**
   * <code>optional .ProtoSettings.Theme currentTheme = 5;</code>
   */
  public int getCurrentThemeValue() {
    return currentTheme_;
  }
  /**
   * <code>optional .ProtoSettings.Theme currentTheme = 5;</code>
   */
  public com.ch8n.thatsmine.ProtoSettings.Theme getCurrentTheme() {
    com.ch8n.thatsmine.ProtoSettings.Theme result = com.ch8n.thatsmine.ProtoSettings.Theme.forNumber(currentTheme_);
    return result == null ? com.ch8n.thatsmine.ProtoSettings.Theme.UNRECOGNIZED : result;
  }
  /**
   * <code>optional .ProtoSettings.Theme currentTheme = 5;</code>
   */
  private void setCurrentThemeValue(int value) {
      currentTheme_ = value;
  }
  /**
   * <code>optional .ProtoSettings.Theme currentTheme = 5;</code>
   */
  private void setCurrentTheme(com.ch8n.thatsmine.ProtoSettings.Theme value) {
    if (value == null) {
      throw new NullPointerException();
    }
    
    currentTheme_ = value.getNumber();
  }
  /**
   * <code>optional .ProtoSettings.Theme currentTheme = 5;</code>
   */
  private void clearCurrentTheme() {
    
    currentTheme_ = 0;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (notificationEnabled_ != false) {
      output.writeBool(1, notificationEnabled_);
    }
    if (loggedIn_ != false) {
      output.writeBool(2, loggedIn_);
    }
    if (guestMode_ != false) {
      output.writeBool(3, guestMode_);
    }
    if (activeUser_ != null) {
      output.writeMessage(4, getActiveUser());
    }
    if (currentTheme_ != com.ch8n.thatsmine.ProtoSettings.Theme.Light.getNumber()) {
      output.writeEnum(5, currentTheme_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (notificationEnabled_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, notificationEnabled_);
    }
    if (loggedIn_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, loggedIn_);
    }
    if (guestMode_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, guestMode_);
    }
    if (activeUser_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getActiveUser());
    }
    if (currentTheme_ != com.ch8n.thatsmine.ProtoSettings.Theme.Light.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, currentTheme_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static com.ch8n.thatsmine.ProtoSettings parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ch8n.thatsmine.ProtoSettings parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ch8n.thatsmine.ProtoSettings parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ch8n.thatsmine.ProtoSettings parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ch8n.thatsmine.ProtoSettings parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.ch8n.thatsmine.ProtoSettings parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.ch8n.thatsmine.ProtoSettings parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.ch8n.thatsmine.ProtoSettings parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.ch8n.thatsmine.ProtoSettings parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.ch8n.thatsmine.ProtoSettings parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ch8n.thatsmine.ProtoSettings prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code ProtoSettings}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.ch8n.thatsmine.ProtoSettings, Builder> implements
      // @@protoc_insertion_point(builder_implements:ProtoSettings)
      com.ch8n.thatsmine.ProtoSettingsOrBuilder {
    // Construct using com.ch8n.thatsmine.ProtoSettings.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional bool notification_enabled = 1;</code>
     */
    public boolean getNotificationEnabled() {
      return instance.getNotificationEnabled();
    }
    /**
     * <code>optional bool notification_enabled = 1;</code>
     */
    public Builder setNotificationEnabled(boolean value) {
      copyOnWrite();
      instance.setNotificationEnabled(value);
      return this;
    }
    /**
     * <code>optional bool notification_enabled = 1;</code>
     */
    public Builder clearNotificationEnabled() {
      copyOnWrite();
      instance.clearNotificationEnabled();
      return this;
    }

    /**
     * <code>optional bool loggedIn = 2;</code>
     */
    public boolean getLoggedIn() {
      return instance.getLoggedIn();
    }
    /**
     * <code>optional bool loggedIn = 2;</code>
     */
    public Builder setLoggedIn(boolean value) {
      copyOnWrite();
      instance.setLoggedIn(value);
      return this;
    }
    /**
     * <code>optional bool loggedIn = 2;</code>
     */
    public Builder clearLoggedIn() {
      copyOnWrite();
      instance.clearLoggedIn();
      return this;
    }

    /**
     * <code>optional bool guestMode = 3;</code>
     */
    public boolean getGuestMode() {
      return instance.getGuestMode();
    }
    /**
     * <code>optional bool guestMode = 3;</code>
     */
    public Builder setGuestMode(boolean value) {
      copyOnWrite();
      instance.setGuestMode(value);
      return this;
    }
    /**
     * <code>optional bool guestMode = 3;</code>
     */
    public Builder clearGuestMode() {
      copyOnWrite();
      instance.clearGuestMode();
      return this;
    }

    /**
     * <code>optional .ProtoSettings.ActiveUser activeUser = 4;</code>
     */
    public boolean hasActiveUser() {
      return instance.hasActiveUser();
    }
    /**
     * <code>optional .ProtoSettings.ActiveUser activeUser = 4;</code>
     */
    public com.ch8n.thatsmine.ProtoSettings.ActiveUser getActiveUser() {
      return instance.getActiveUser();
    }
    /**
     * <code>optional .ProtoSettings.ActiveUser activeUser = 4;</code>
     */
    public Builder setActiveUser(com.ch8n.thatsmine.ProtoSettings.ActiveUser value) {
      copyOnWrite();
      instance.setActiveUser(value);
      return this;
      }
    /**
     * <code>optional .ProtoSettings.ActiveUser activeUser = 4;</code>
     */
    public Builder setActiveUser(
        com.ch8n.thatsmine.ProtoSettings.ActiveUser.Builder builderForValue) {
      copyOnWrite();
      instance.setActiveUser(builderForValue);
      return this;
    }
    /**
     * <code>optional .ProtoSettings.ActiveUser activeUser = 4;</code>
     */
    public Builder mergeActiveUser(com.ch8n.thatsmine.ProtoSettings.ActiveUser value) {
      copyOnWrite();
      instance.mergeActiveUser(value);
      return this;
    }
    /**
     * <code>optional .ProtoSettings.ActiveUser activeUser = 4;</code>
     */
    public Builder clearActiveUser() {  copyOnWrite();
      instance.clearActiveUser();
      return this;
    }

    /**
     * <code>optional .ProtoSettings.Theme currentTheme = 5;</code>
     */
    public int getCurrentThemeValue() {
      return instance.getCurrentThemeValue();
    }
    /**
     * <code>optional .ProtoSettings.Theme currentTheme = 5;</code>
     */
    public Builder setCurrentThemeValue(int value) {
      copyOnWrite();
      instance.setCurrentThemeValue(value);
      return this;
    }
    /**
     * <code>optional .ProtoSettings.Theme currentTheme = 5;</code>
     */
    public com.ch8n.thatsmine.ProtoSettings.Theme getCurrentTheme() {
      return instance.getCurrentTheme();
    }
    /**
     * <code>optional .ProtoSettings.Theme currentTheme = 5;</code>
     */
    public Builder setCurrentTheme(com.ch8n.thatsmine.ProtoSettings.Theme value) {
      copyOnWrite();
      instance.setCurrentTheme(value);
      return this;
    }
    /**
     * <code>optional .ProtoSettings.Theme currentTheme = 5;</code>
     */
    public Builder clearCurrentTheme() {
      copyOnWrite();
      instance.clearCurrentTheme();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ProtoSettings)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.ch8n.thatsmine.ProtoSettings();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.ch8n.thatsmine.ProtoSettings other = (com.ch8n.thatsmine.ProtoSettings) arg1;
        notificationEnabled_ = visitor.visitBoolean(notificationEnabled_ != false, notificationEnabled_,
            other.notificationEnabled_ != false, other.notificationEnabled_);
        loggedIn_ = visitor.visitBoolean(loggedIn_ != false, loggedIn_,
            other.loggedIn_ != false, other.loggedIn_);
        guestMode_ = visitor.visitBoolean(guestMode_ != false, guestMode_,
            other.guestMode_ != false, other.guestMode_);
        activeUser_ = visitor.visitMessage(activeUser_, other.activeUser_);
        currentTheme_ = visitor.visitInt(currentTheme_ != 0, currentTheme_,    other.currentTheme_ != 0, other.currentTheme_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                notificationEnabled_ = input.readBool();
                break;
              }
              case 16: {

                loggedIn_ = input.readBool();
                break;
              }
              case 24: {

                guestMode_ = input.readBool();
                break;
              }
              case 34: {
                com.ch8n.thatsmine.ProtoSettings.ActiveUser.Builder subBuilder = null;
                if (activeUser_ != null) {
                  subBuilder = activeUser_.toBuilder();
                }
                activeUser_ = input.readMessage(com.ch8n.thatsmine.ProtoSettings.ActiveUser.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(activeUser_);
                  activeUser_ = subBuilder.buildPartial();
                }

                break;
              }
              case 40: {
                int rawValue = input.readEnum();

                currentTheme_ = rawValue;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.ch8n.thatsmine.ProtoSettings.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:ProtoSettings)
  private static final com.ch8n.thatsmine.ProtoSettings DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ProtoSettings();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.ch8n.thatsmine.ProtoSettings getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ProtoSettings> PARSER;

  public static com.google.protobuf.Parser<ProtoSettings> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

