// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: settings_pb.proto

package com.ch8n.thatsmine;

public final class SettingsPb {
  private SettingsPb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
